# Generated by Django 4.2.10 on 2024-04-29 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_alter_entry_created_alter_source_feed_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='index',
        ),
    ]
