# Generated by Django 5.0.6 on 2024-05-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0014_remove_source_interval_remove_source_is_cloudflare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='subtitle',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
