# Generated by Django 5.0.6 on 2024-05-26 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_alter_source_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enclosure',
            old_name='post',
            new_name='entry',
        ),
    ]
