# Generated by Django 5.1.6 on 2025-02-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_alter_entry_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='due_poll',
            new_name='due_fetch',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='last_polled',
            new_name='last_feched',
        ),
    ]
