# Generated by Django 5.1.6 on 2025-02-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0018_rename_due_poll_source_due_fetch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='last_change',
        ),
        migrations.RemoveField(
            model_name='source',
            name='max_index',
        ),
        migrations.RemoveField(
            model_name='source',
            name='num_subs',
        ),
        migrations.AddField(
            model_name='source',
            name='min_interval',
            field=models.FloatField(default=3600),
        ),
    ]
