# Generated by Django 5.1.6 on 2025-02-28 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0019_remove_source_last_change_remove_source_max_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='due_fetch',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
